Admin validation
tomered/smart-campus-backend pull request #11
Opened 2024-09-12 19:08 UTC by yuvalelarat

added validateAdmin middleware on "/api/validate-admin"

2024-09-12 19:08 UTC, yuvalelarat commented
notice me if its good enough

2024-09-14 10:09 UTC, tomered commented on src/index.ts
> +app.use("/api/validate-admin", authenticateUser, validateAdmin);
line 19 should look like this:
app.use("/api", authenticateUser, authenticateUser, validateAdmin, adminEndpoint);
delete line 20 and create adminEndpoint

2024-09-14 10:09 UTC, tomered commented on src/middleware/validateAdmin.ts
> +
please add documentation and comments

2024-09-14 10:09 UTC, tomered commented on src/middleware/validateAdmin.ts
> +};
add next to middleware function

2024-09-14 10:11 UTC, tomered requested changes

2024-09-14 10:11 UTC, tomered commented on src/index.ts
> +app.use("/api/validate-admin", authenticateUser, validateAdmin);
line 19 should look like this:
app.use("/api", authenticateUser, authenticateUser, validateAdmin, adminEndpoint);
delete line 20 and create adminEndpoint

2024-09-14 11:23 UTC, yuvalelarat commented
I have added adminEndpoint.ts in routes folder and changed to app.use("/api", authenticateUser, validateAdmin, adminEndpoint);
is that what you meant?

2024-09-14 13:23 UTC, yuvalelarat commented
done.

2024-09-14 16:59 UTC, tomered approved these changes

2024-09-14 16:59 UTC, merged