Forgotten password
tomered/smart-campus-backend pull request #16
Opened 2024-10-01 14:58 UTC by SaharLevy

Changes: Adding 2 routes.

POST /manage-password/forgot-password
POST /manage-password/reset-password

2024-10-30 04:28 UTC, tomered requested changes

2024-10-30 04:28 UTC, tomered commented on src/routes/forgotPassword.ts
> +      host: "smtp.gmail.com",
please put it in env file please

2024-11-03 16:08 UTC, yuvalelarat commented on src/routes/forgotPassword.ts
> +      host: "smtp.gmail.com",
done

2024-11-03 16:09 UTC, yuvalelarat commented
ready for 2nd review

2024-11-07 14:51 UTC, merged